language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
before_script:
  - "/home/travis/.phpenv/versions/5.4/bin/composer self-update"
  - "composer update --prefer-source"
script: sh src/Scripts/test_strata
